version: 2
enable-beta-ecosystems: true

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "danestves"
    assignees:
      - "danestves"

  - package-ecosystem: bun
    directory: /
    schedule:
      interval: "weekly"
    reviewers:
      - "danestves"
    assignees:
      - "danestves"
