name: Bump version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semver type of new version (major / minor / patch)"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Setup Git
        run: |
          git config user.name '${{ secrets.GIT_USER_NAME }}'
          git config user.email '${{ secrets.GIT_USER_EMAIL }}'

      - name: bump version
        run: npm version ${{ github.event.inputs.version }}

      - name: Push latest version
        run: git push origin main --follow-tags
